export const webUsageData=[
  {
    id: 1,
    product: "2020 Hoodie",
    "Numbers of Users Visited": 310,
    "Average Time Viewed(min)": 5,
    "Total Number Purchased": 20,
  },
  {
    id: 2,
    product: "2020 Pants",
    "Numbers of Users Visited": 120,
    "Average Time Viewed(min)": 4.2,
    "Total Number Purchased": 15,
  },
  {
    id: 3,
    product: "2020 Mugcup",
    "Numbers of Users Visited": 250,
    "Average Time Viewed(min)": 1.3,
    "Total Number Purchased": 51,
  },
  {
    id: 4,
    product: "2020 Jacket",
    "Numbers of Users Visited": 422,
    "Average Time Viewed(min)": 12.4,
    "Total Number Purchased": 500,
  },
  {
    id: 5,
    product: "2019 Hoodie",
    "Numbers of Users Visited": 622,
    "Average Time Viewed(min)": 5.4,
    "Total Number Purchased": 31,
  },
  {
    id: 6,
    product: "2020 Shoes",
    "Numbers of Users Visited": 322,
    "Average Time Viewed(min)": 11.4,
    "Total Number Purchased": 16,
  },
  {
    id: 7,
    product: "2020 Shorts",
    "Numbers of Users Visited": 232,
    "Average Time Viewed(min)": 3.4,
    "Total Number Purchased": 66,
  },
  {
    id: 8,
    product: "2017 Legendary Jacket",
    "Numbers of Users Visited": 322,
    "Average Time Viewed(min)": 15.4,
    "Total Number Purchased": 102,
  },
  {
    id: 9,
    product: "2020 T-Shirts",
    "Numbers of Users Visited": 12,
    "Average Time Viewed(min)": 4.4,
    "Total Number Purchased": 12,
  },
  {
    id: 10,
    product: "SBU Tumblr",
    "Numbers of Users Visited": 212,
    "Average Time Viewed(min)": 8.4,
    "Total Number Purchased": 29,
  }
];