import dummy from "../../../images/dummy.jpg";
import member1 from "../../../images/member1.jpg";

export const DataMembers = [
  {
    id: "1",
    name: "Rebecca",
    position: "President",
    date: "Joined 2018-09",
    description:
      "Leads MSC and its members to make unique merchandise for students around campus.",
    img: member1,
    contact: "rebecca@msc.com",
  },

  {
    id: "2",
    name: "Person_2",
    position: "Vice-President",
    date: "Joined Date",
    description: "Description the person's role in MSC",
    img: member1,
    contact: "contact",
  },
  {
    id: "3",
    name: "Person_3",
    position: "Treasurer",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "4",
    name: "Person_4",
    position: "Secretary",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "5",
    name: "Person_5",
    position: "Lead Designer",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "6",
    name: "Person_6",
    position: "Retail Shop Manager",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "7",
    name: "Person_7",
    position: "Member",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "8",
    name: "Person_8",
    position: "Member",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "9",
    name: "Person_9",
    position: "Member",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "10",
    name: "Person_10",
    position: "Member",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "11",
    name: "Person_11",
    position: "Member",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "12",
    name: "Person_12",
    position: "Member",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "13",
    name: "Person_13",
    position: "Member",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "14",
    name: "Person_14",
    position: "Member",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
  {
    id: "15",
    name: "Person_15",
    position: "Member",
    date: "Joined Date",
    description: "Description the person's role in MSC ",
    img: member1,
    contact: "contact",
  },
];
